
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleEle_B_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleEle_B_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleEle_C/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleEle_D/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleEle_E/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleEle_F/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleEle_G/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleEle_H_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleEle_H_3/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleMu_B_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleMu_B_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleMu_C/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleMu_D/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleMu_E/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleMu_F/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleMu_G/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleMu_H_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_Data_SingleMu_H_3/

#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ggZH_HSSbbbb_MS_40_ctauS_0/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ggZH_HSSbbbb_MS_40_ctauS_0p05/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ggZH_HSSbbbb_MS_40_ctauS_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ggZH_HSSbbbb_MS_40_ctauS_10/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ggZH_HSSbbbb_MS_40_ctauS_100/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ggZH_HSSbbbb_MS_40_ctauS_1000/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ggZH_HSSbbbb_MS_40_ctauS_10000/
#
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY50_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY50_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY5to50_HT100to200_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY5to50_HT100to200_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY5to50_HT200to400_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY5to50_HT200to400_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY5to50_HT400to600_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY5to50_HT400to600_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY5to50_HT600toInf_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY5to50_HT600toInf_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_DY5to50_HT70to100/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_GJets_HT100to200_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_GJets_HT100to200_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_GJets_HT200to400_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_GJets_HT200to400_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_GJets_HT400to600_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_GJets_HT400to600_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_GJets_HT40to100_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_GJets_HT40to100_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_GJets_HT600toInf_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_GJets_HT600toInf_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_STs/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_STt/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_STtW_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_STtW_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_STtbar/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_STtbarW_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_STtbarW_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_TTtoLL_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_TTtoLL_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_TTtoLfromT_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_TTtoLfromT_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_TTtoLfromTbar_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_TTtoLfromTbar_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_WG/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_WJets_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_WJets_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_WWToLNuLNu/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_WWToLNuQQ_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_WWToLNuQQ_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_WZToLLLNu/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_WZToLNu2QorQQ2L/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_WZToLNuNuNu/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ZG/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ZH_Hbb_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ZH_Hbb_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ZZToLLLL/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ZZToLLNuNu/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ZZToLLQQ/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ZZToNuNuQQ/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ggZH_Hbb_1/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ggZH_Hbb_2/
#crab resubmit -d gitignore/${nversion}/crabsubmits_${nversion}/crab_ggZH_Hbb_3/
#
