
root -l 'rmhisto.C("DY50_ALLCALOJETS_0.root")'
root -l 'rmhisto.C("DY50_ALLCALOJETS_1.root")'
root -l 'rmhisto.C("DY50_ALLCALOJETS_2.root")'
root -l 'rmhisto.C("DY50_ALLCALOJETS_3.root")'
root -l 'rmhisto.C("DY50_ALLCALOJETS_4.root")'
root -l 'rmhisto.C("DY50_ALLCALOJETS_5.root")'
root -l 'rmhisto.C("DY50_ALLCALOJETS_6.root")'
root -l 'rmhisto.C("DY50_ALLCALOJETS_7.root")'
root -l 'rmhisto.C("DY50_BASICCALOJETS1PT20_0.root")'
root -l 'rmhisto.C("DY50_BASICCALOJETS1PT20_1.root")'
root -l 'rmhisto.C("DY50_BASICCALOJETS1PT20_2.root")'
root -l 'rmhisto.C("DY50_BASICCALOJETS1PT20_3.root")'
root -l 'rmhisto.C("DY50_BASICCALOJETS1PT20_4.root")'
root -l 'rmhisto.C("DY50_BASICCALOJETS1PT20_5.root")'
root -l 'rmhisto.C("DY50_BASICCALOJETS1PT20_6.root")'
root -l 'rmhisto.C("DY50_BASICCALOJETS1PT20_7.root")'
